# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Manaita < Formula
  desc "Simple Markdown-Driven Code Generator written by Go"
  homepage "https://github.com/igtm/manaita"
  version "1.0.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/igtm/manaita/releases/download/v1.0.3/manaita_1.0.3_Darwin_arm64.tar.gz"
      sha256 "a89ad403ff5f82fd8504787225da66929dbe57bd579f3d7e2de840266f87be49"

      def install
        bin.install "manaita"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/igtm/manaita/releases/download/v1.0.3/manaita_1.0.3_Darwin_x86_64.tar.gz"
      sha256 "267389de3b318a751a9fccdfbc09b5534b053f470db1ff54cddf3ee75974b0bf"

      def install
        bin.install "manaita"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/igtm/manaita/releases/download/v1.0.3/manaita_1.0.3_Linux_arm64.tar.gz"
      sha256 "0d92a79f50f4a7b79a4d38e0c9ad8122655eb9173908f62339eb4751810dbd99"

      def install
        bin.install "manaita"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/igtm/manaita/releases/download/v1.0.3/manaita_1.0.3_Linux_x86_64.tar.gz"
      sha256 "799053f9c6316df90b4ca4a954be32dbd42bde2253356d6c393ff6bec98d3865"

      def install
        bin.install "manaita"
      end
    end
  end
end
