# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Manaita < Formula
  desc "Simple Markdown-Driven Scaffolding tool written by Go"
  homepage "https://github.com/igtm/manaita"
  version "1.0.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/igtm/manaita/releases/download/v1.0.5/manaita_1.0.5_Darwin_x86_64.tar.gz"
      sha256 "af251b63013ddf6d24a84a092a8163413476fe0d9366848749197d3eb5a107c8"

      def install
        bin.install "manaita"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/igtm/manaita/releases/download/v1.0.5/manaita_1.0.5_Darwin_arm64.tar.gz"
      sha256 "082343eea37df24c0ab97b4ca6894c9dd2f253405acc70450a734372aedd91dc"

      def install
        bin.install "manaita"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/igtm/manaita/releases/download/v1.0.5/manaita_1.0.5_Linux_arm64.tar.gz"
      sha256 "a98cba14f5a4ab0b706efe3a2a3c6b01e63af4fc988d64d858d67565ecd080bb"

      def install
        bin.install "manaita"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/igtm/manaita/releases/download/v1.0.5/manaita_1.0.5_Linux_x86_64.tar.gz"
      sha256 "c03e274fac9c822dbe9da74789c1dc6ed0c0fb23001e4e3adda91aff964e0bf1"

      def install
        bin.install "manaita"
      end
    end
  end
end
