# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Manaita < Formula
  desc "Simple Markdown-Driven Scaffolding tool written by Go"
  homepage "https://github.com/igtm/manaita"
  version "1.0.8"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/igtm/manaita/releases/download/v1.0.8/manaita_1.0.8_Darwin_x86_64.tar.gz"
      sha256 "4489b59a938d14649e0540112355afa376f7d4de2db4d074fb6098c1fd37ed1f"

      def install
        bin.install "manaita"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/igtm/manaita/releases/download/v1.0.8/manaita_1.0.8_Darwin_arm64.tar.gz"
      sha256 "d0429fa7d4273edc6253f9269031a0fbe5759ff61a9f70f67025db327a97b532"

      def install
        bin.install "manaita"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/igtm/manaita/releases/download/v1.0.8/manaita_1.0.8_Linux_x86_64.tar.gz"
      sha256 "1ba366435a6036136dd6a0a1ec7fbf4e81a55181bd81c5e59a5a9b572f192da8"

      def install
        bin.install "manaita"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/igtm/manaita/releases/download/v1.0.8/manaita_1.0.8_Linux_arm64.tar.gz"
      sha256 "81286b9c2bb78f9b696033267e8493494dc0dba916dce304afe3e33ed9330b99"

      def install
        bin.install "manaita"
      end
    end
  end
end
